services:
  - type: web
    name: sleep-apnea-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT flask-backend-render:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: ANALYSIS_FOLDER
        value: /tmp/analysis_results
